// src/pages/Analytics.jsx
import { useEffect, useState } from "react";
import API from "../api/axios";
import CustomerPieChart from "../components/CustomerPieChart";
import RevenueBarChart from "../components/RevenueBarChart";

const Analytics = () => {
  const [stats, setStats] = useState({});
  const [insights, setInsights] = useState("");

  useEffect(() => {
    loadAnalytics();
  }, []);

  const loadAnalytics = async () => {
    try {
      const { data } = await API.get("/analytics");
      setStats(data);

      const insightData = await API.post("/analytics/insights", data);
      setInsights(insightData.data.insights);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <section className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-semibold tracking-tight text-slate-50">
            Analytics
          </h1>
          <p className="mt-1 text-sm text-slate-400 max-w-xl">
            Visualize customer behavior, revenue performance, and AI‑generated
            insights from your campaigns.
          </p>
        </div>
      </section>

      {/* High-level metrics */}
      <section className="grid gap-4 md:grid-cols-5">
        <MetricCard
          label="Total Customers"
          value={stats.totalCustomers}
        />
        <MetricCard
          label="VIP Customers"
          value={stats.vipCustomers}
        />
        <MetricCard
          label="Active Customers"
          value={stats.activeCustomers}
        />
        <MetricCard
          label="Inactive Customers"
          value={stats.inactiveCustomers}
        />
        <MetricCard
          label="Revenue"
          value={stats.totalRevenue ? `₹${stats.totalRevenue}` : "₹0"}
          accent="emerald"
        />
      </section>

      {/* Charts grid */}
      <section className="grid gap-4 lg:grid-cols-2">
        {/* Customer distribution */}
        <div className="rounded-2xl bg-gradient-to-b from-slate-900/80 via-slate-950 to-black border border-white/10 shadow-[0_20px_60px_rgba(15,23,42,0.9)] p-4 sm:p-5">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h2 className="text-sm font-semibold text-slate-100">
                Customer Distribution
              </h2>
              <p className="text-[11px] text-slate-400">
                Active vs inactive customers in your CRM.
              </p>
            </div>
          </div>
          <div className="h-64">
            <CustomerPieChart
              active={stats.activeCustomers}
              inactive={stats.inactiveCustomers}
            />
          </div>
        </div>

        {/* Revenue analytics */}
        <div className="rounded-2xl bg-gradient-to-b from-slate-900/80 via-slate-950 to-black border border-white/10 shadow-[0_20px_60px_rgba(15,23,42,0.9)] p-4 sm:p-5">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h2 className="text-sm font-semibold text-slate-100">
                Revenue Analytics
              </h2>
              <p className="text-[11px] text-slate-400">
                Revenue trends across segments and time.
              </p>
            </div>
          </div>
          <div className="h-64">
            <RevenueBarChart stats={stats} />
          </div>
        </div>
      </section>

      {/* AI Insights */}
      <section className="rounded-2xl bg-gradient-to-r from-indigo-500/15 via-slate-950 to-fuchsia-500/20 border border-indigo-400/40 shadow-[0_24px_80px_rgba(79,70,229,0.9)] p-4 sm:p-5">
        <div className="flex items-center justify-between mb-2">
          <div>
            <h2 className="text-sm font-semibold text-slate-50">
              AI Insights
            </h2>
            <p className="text-[11px] text-slate-200">
              Generated by the Analytics Agent based on your latest data.
            </p>
          </div>
          <span className="hidden sm:inline-flex items-center gap-1 rounded-full bg-black/40 px-3 py-1 text-[10px] text-indigo-100 border border-indigo-300/40">
            <span className="h-1.5 w-1.5 rounded-full bg-indigo-300 animate-ping" />
            Updated on data refresh
          </span>
        </div>
        <pre className="mt-2 max-h-72 overflow-y-auto whitespace-pre-wrap text-xs leading-relaxed text-slate-100/90 bg-black/25 rounded-xl p-3 border border-white/10">
          {insights || "AI has not generated any insights yet."}
        </pre>
      </section>
    </div>
  );
};

/**
 * MetricCard: small reusable card for metrics
 */
const MetricCard = ({ label, value, accent = "indigo" }) => {
  const accentMap = {
    indigo:
      "from-indigo-500/15 via-slate-900/80 to-slate-950 border-indigo-400/40 shadow-[0_18px_55px_rgba(79,70,229,0.6)]",
    emerald:
      "from-emerald-500/15 via-slate-900/80 to-slate-950 border-emerald-400/40 shadow-[0_18px_55px_rgba(16,185,129,0.6)]",
  };

  const accentClasses = accentMap[accent] || accentMap.indigo;

  return (
    <div
      className={[
        "rounded-2xl bg-gradient-to-br",
        accentClasses,
        "p-3 sm:p-4 flex flex-col justify-between hover:-translate-y-0.5 hover:shadow-[0_24px_70px_rgba(15,23,42,1)] transition-all duration-200 border",
      ].join(" ")}
    >
      <span className="text-[11px] font-medium text-slate-200">
        {label}
      </span>
      <span className="mt-1 text-lg font-semibold text-slate-50">
        {value ?? 0}
      </span>
    </div>
  );
};

export default Analytics;