// src/pages/Campaigns.jsx
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import API from "../api/axios";

const Campaigns = () => {
  const [campaigns, setCampaigns] = useState([]);
  const navigate = useNavigate();

  useEffect(() => {
    fetchCampaigns();
  }, []);

  const fetchCampaigns = async () => {
    try {
      const { data } = await API.get("/campaigns");
      setCampaigns(data);
    } catch (error) {
      console.log(error);
    }
  };

  // sendCampaign exists in your project already – we just keep calling it
  const sendCampaign = async (campaign) => {
    try {
      // If you already have implementation, remove this and use your existing one.
      // Example placeholder:
      await API.put(`/campaigns/${campaign._id}/status`, {
        status: "Sent",
      });
      fetchCampaigns();
    } catch (error) {
      console.log(error);
    }
  };

  const getStatusClasses = (status) => {
    if (status === "Sent") {
      return "bg-emerald-500/15 text-emerald-300 border-emerald-400/40";
    }
    if (status === "Failed") {
      return "bg-rose-500/15 text-rose-300 border-rose-400/40";
    }
    return "bg-amber-500/15 text-amber-300 border-amber-400/40";
  };

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <section className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-semibold tracking-tight text-slate-50">
            Campaign History
          </h1>
          <p className="mt-1 text-sm text-slate-400 max-w-xl">
            Review, resend, and monitor the status of all AI‑generated campaigns.
          </p>
        </div>
      </section>

      {/* Campaigns table card */}
      <section className="rounded-2xl bg-gradient-to-b from-slate-900/85 via-slate-950 to-black border border-white/10 shadow-[0_22px_70px_rgba(15,23,42,0.9)] p-4 sm:p-5">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h2 className="text-sm font-semibold text-slate-100">
              Campaigns
            </h2>
            <p className="text-[11px] text-slate-400">
              {campaigns.length} campaigns generated by your AI agents.
            </p>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full text-xs border-separate border-spacing-y-1">
            <thead>
              <tr className="text-[11px] text-slate-400">
                <th className="text-left px-3 py-2 font-medium">Name</th>
                <th className="text-left px-3 py-2 font-medium">Goal</th>
                <th className="text-left px-3 py-2 font-medium">Status</th>
                <th className="text-center px-3 py-2 font-medium">View</th>
                <th className="text-center px-3 py-2 font-medium">Send</th>
              </tr>
            </thead>
            <tbody>
              {campaigns.length === 0 && (
                <tr>
                  <td
                    colSpan={5}
                    className="px-3 py-4 text-center text-[11px] text-slate-500"
                  >
                    No campaigns yet. Generate a campaign using your AI agents
                    and it will appear here.
                  </td>
                </tr>
              )}

              {campaigns.map((campaign) => (
                <tr key={campaign._id}>
                  <td className="px-3 py-2 align-top">
                    <div className="rounded-xl bg-slate-900/70 border border-white/10 px-3 py-2 flex flex-col">
                      <span className="text-xs font-medium text-slate-100">
                        {campaign.campaignName}
                      </span>
                      {campaign.channel && (
                        <span className="mt-0.5 text-[10px] text-slate-400">
                          Channel: {campaign.channel}
                        </span>
                      )}
                    </div>
                  </td>

                  <td className="px-3 py-2 align-top text-xs text-slate-200">
                    {campaign.goal || "-"}
                  </td>

                  <td className="px-3 py-2 align-top">
                    <span
                      className={[
                        "inline-flex items-center rounded-full px-2.5 py-1 text-[10px] border",
                        getStatusClasses(campaign.status),
                      ].join(" ")}
                    >
                      <span className="h-1.5 w-1.5 rounded-full bg-current opacity-80 mr-1.5" />
                      {campaign.status}
                    </span>
                  </td>

                  <td className="px-3 py-2 align-top text-center">
                    <button
                      type="button"
                      onClick={() =>
                        navigate(`/campaign/${campaign._id}`)
                      }
                      className="inline-flex items-center justify-center rounded-xl bg-indigo-500 hover:bg-indigo-400 px-3 py-1.5 text-[11px] font-semibold text-white shadow-[0_12px_35px_rgba(79,70,229,0.85)] transition-colors duration-150"
                    >
                      View
                    </button>
                  </td>

                  <td className="px-3 py-2 align-top text-center">
                    <button
                      type="button"
                      onClick={() => sendCampaign(campaign)}
                      className="inline-flex items-center justify-center rounded-xl bg-emerald-500 hover:bg-emerald-400 px-3 py-1.5 text-[11px] font-semibold text-white shadow-[0_12px_35px_rgba(16,185,129,0.85)] transition-colors duration-150"
                    >
                      Send
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
};

export default Campaigns;